[package]
name = "darling_macro"
version = "0.6.1"
authors = ["Ted Driggs <ted.driggs@outlook.com>"]
repository = "https://github.com/TedDriggs/darling"
description = """
Internal support for a proc-macro library for reading attributes into structs when
implementing custom derives. Use https://crates.io/crates/darling in your code.
"""
license = "MIT"

[dependencies]
quote = "0.5"
syn = "0.13"
darling_core = { version = "=0.6.1", path = "../core" }

[lib]
proc-macro = true
